name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, linux/arm64'
          package: ''
          name: 'ddns'
          compress: 'true'
          dest: 'dist'

