name: Image

on:
  push:
    branches: [ master ]
    tags: ["*"]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=releaseName;]$(if [ "${GITHUB_REF##*/}" = "master" ]; then echo "latest"; else echo "${GITHUB_REF##*/}"; fi)"
          echo "##[set-output name=buildStamp;]"$(date -u '+%Y-%m-%d_%I:%M:%S%p')
        id: args

      - name: echo debug msg
        run: |
          echo "build ${{ github.ref }} tag image"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Run buildx
        run: |
          docker buildx build -t penitence/ddns:${{ steps.args.outputs.releaseName }} --platform=linux/arm64,linux/amd64 \
            --output "type=image,push=false" \
            --build-arg gitCommit=${GITHUB_SHA} --build-arg buildStamp=${steps.args.outputs.buildStamp} \
            .